### ISSUE TITLE
Different Global Environments: PBI vs. SDK - "Environment.*" visible outside of connector

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#114]
In Power BI, the `Environment.*` set of identifiers are only visible from inside a connector. However, in the new SDK, these methods are visible from the .query.pq test file. Is this difference in the public global environment between the SDK and PBI intentional or something that leaked through? :-)

## Repo
Running the below in the SDK returns the list: { "Environment.Libraries", "Environment.Configuration", "Environment.FeatureSwitch" }
Running it in Power BI's Query Editor returns an empty list.
````
let
    Public = Table.FromValue(#shared)[Name],
    JustEnvironment = List.Select(Public, each Text.StartsWith(_, "Environment."))
in
    JustEnvironment
````

**Comment by mattmasson** [comment]
Functions that leaked through.

`Environment.Configuration` and `Environment.FeatureSwitch` are available in an extension/connector context today. They are used by 1st party connectors that need to do things like check which Azure environment they are running in. The functionality isn't fully baked yet, but it will eventually be publicly documented (although I don't think it all relevant to non-MSFT connectors). 

`Environment.Libraries` is what the `pqtest info` command uses to fetch symbol and other details for extensions that have been loaded. I'm not sure offhand why it's not exposed in PQ, but it's probably because it's not very easy to use, and we're still iterating on its functionality.

**Comment by bgribaudo** [comment]
Thanks, @mattmasson.

**Comment by mattmasson** [comment]
I was going back and forth on whether to remove these optional modules from regular pqtest evaluations and/or adding a "power query mode" command line option. I'd like to leave them in for now, as I can see them being useful for a few different test scenarios in the future.

**Comment by bgribaudo** [comment]
Sounds good. Thanks!
