### ISSUE TITLE
Input prompt not working

### ISSUE THREAD

**Issue by RodThurgau** [microsoft/vscode-powerquery-sdk#198]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.2.0

### Platform

Windows

### Architecture

x64

### OS Version

Windows 11

### VSCode version

1.73.1

### Bug Description

I wrote a custom test connector, but in the Connection indow there was no prompt for the input Parameter.

### Steps to Reproduce

1. Replace the Contents function with the following

```
[Version = "1.0.0"]
section temp;
 
[DataSource.Kind="temp", Publish="temp.Publish"]
shared temp.Contents = (value as number) =>
   let
        mylist = List.Numbers(1,value),
        out= Table.FromList(mylist, Splitter.SplitByNothing(), null, null, ExtraValues.Error)
   in
        out;
```

2. Connect to this Custom Connector in Power BI

### Actual Experience

There is no Prompt for "value" when connecting to the Custom Connector
<img width="354" alt="BugSS1" src="https://user-images.githubusercontent.com/28777810/203997940-a22c10aa-d3f3-46b1-b662-176aa34173ad.png">

### Expected Experience

Get a prompt to ask for a numeric value and the created table afterwards

**Comment by mattmasson** [comment]
This looks like a general question about custom connector development rather than an issue with the SDK. You might want to post this in the [discussion section](https://github.com/microsoft/vscode-powerquery-sdk/discussions) instead.

That said, here are some tips for troubleshooting:

- Make sure you've copied the updated .mez file to your Custom Connectors directory
- Close Power BI
- Delete the files in the `%localappdata%\Microsoft\Power BI Desktop\ExtensionCache` directory
- Restart Power BI Desktop 
- Launch the connector from the Get Data dialog  ... using the Recent Sources dialog will pre-populate the function parameters
