### ISSUE TITLE
Issues from prior SDK?

### ISSUE THREAD

**Issue by andyphenix** [microsoft/vscode-powerquery-sdk#209]
Redirected here from old SDK repo --> https://github.com/microsoft/DataConnectors

Old repo had a number of open issues that we were tracking. Issues now appear to be turned off on the old repo - were those issues ported over to this new SDK?

**Comment by mattmasson** [comment]
No, we didn't port the issues over since the majority of the issues in that repo weren't actually related to the SDK bits. Do you have details of the issues you were tracking? 

/cc: @ptyx507x

**Comment by andyphenix** [comment]
Yes, issues referenced in this forum thread [1] wrt lack of support in creating relationships via the custom data connector.

[1] https://community.powerbi.com/t5/Power-Query/Custom-data-connector-relationships/td-p/537228

**Comment by ptyx507x** [comment]
Thank you for bringing this to our attention, @andyphenix!

My name is Miguel Escobar and I'm the Product Manager behind the Power Query SDK.

I've had a chance to review the situation with the relationships and connectors in Power Query. At the current time there are some pieces that we need to invest on in order to provide a way for connector developers to set automatic relationship recognition through the SDK. This is why you're seeing some issues related to that capability.

The steps that we're taking at the moment are to take down the articles related to relationship creation in the Power Query SDK and internally we're tracking the work to enable such functionality around the SDK and relationships to work without issues.

I do highly encourage you to post an idea on the official [Power BI ideas site](https://ideas.powerbi.com/ideas/) so that we can track the demand for it which will help us prioritize such work.

Again, thank you for bringing this to our attention and let us know if there's anything else that we could help you with.

**Comment by andyphenix** [comment]
In addition to the (now deleted) SDK issues, an entry was posted to the Power BI ideas site back in 2020 --> https://ideas.powerbi.com/ideas/idea/?ideaid=d53a4a2f-4904-43b3-a831-a766f7bbce49

**Comment by ptyx507x** [comment]
Thank you for sharing the link! Please continue sharing your feedback about the SDK. Let us know what you think about the new SDK in Visual Studio Code and if you find any issues / bugs.
