### ISSUE TITLE
Refresh credentials

### ISSUE THREAD

**Issue by simon-r-watson** [microsoft/vscode-powerquery-sdk#255]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.2.2

### Platform

Windows

### Architecture

x64

### VSCode version

1.76.2

### Bug Description

Refresh credentials option it the Power Query SDK option doesn't seem to call the Refresh function in the .pq file.

The logs in the console does make it seem like it is running correctly and is successful (as per logs below from the console), but using Fiddler show's no API calls are being made, and no errors are reported by the SDK. Once the initial access token expires, further calls to the API fail due to auth.

This makes it hard to troubleshoot whether refresh is working correctly.

Timezone here is UTC+8, "expires" is just UTC 
```
[8:27:11 PM]	[Info]	[Task found] c:\Users\wsadmin\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.2-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.114.4\tools\PQTest.exe refresh-credential
				--extension "v:\Gitlab\power-bi-general\******\******\bin\AnyCPU\Debug\******.mez"
				--queryFile "v:\Gitlab\power-bi-general\******\******\******.query.pq"
				--prettyPrint
[8:27:12 PM]	[Info]	RefreshCredential result {
    "Details": {
        "DataSource": {
            "Kind": "******",
            "NormalizedPath": "{\"library\":\"legal\",\"docId\":\"31.1\",\"customerId\":\"1\"}",
            "Path": "{\"library\":\"legal\",\"docId\":\"31.1\",\"customerId\":\"1\"}"
        },
        "AuthenticationKind": "OAuth2",
        "Properties": {
            "AccessToken": "******",
            "Expires": "Fri, 17 Mar 2023 12:15:59 GMT",
            "RefreshToken": "******",
            "token_type": "Bearer",
            "scope": "user"
        }
    },
    "Message": "Credential refresh successful.",
    "Status": "Success"
}
```

### Steps to Reproduce

1. Open a project using OAuth2
2. Implement the Refresh and TokenMethod functions based on this example - https://github.com/microsoft/DataConnectors/blob/master/samples/OAuthPKCE/PKCESample.pq
3. Run "set credentials"
4. Wait several minutes, or until initial access token expires
5. Run "refresh credentials"

### Actual Experience

Credentials aren't refreshed

### Expected Experience

Credentials are refreshed, and console log shows a "expires" time later that the time the log entry was generated at. Or an error message is logged instead of success

**Comment by albertli-msft** [comment]
Hi @simon-r-watson: 

Thanks for using vscode-pq-sdk,

Our ExtensionOAuthFactory would only refresh the token when there were refresh function provided at the Authentication.OAuth like:
![image](https://user-images.githubusercontent.com/69623692/234546453-d4a936d5-b3f4-4294-8776-557ea2d719da.png)

otherwise, it would honestly return the credential back.

Would you mind helping us confirm whether we got that refresh method reference populated correctly in your cases?

Because, when I try to reproduce it on my end using my own githubAppOauth2, it got refreshed correctly every time.

![image](https://user-images.githubusercontent.com/69623692/234547618-125ea34a-f3f8-4c05-ae52-ecea40fcc699.png)


Without refresh method populated in the extension, the SDK would return the original credential without having it refreshed. And that might cause certain confusions, which, in fact, is a correct behavior.

Feel free to reopen it if I were wrong. 

Have a good one. 😀
