### ISSUE TITLE
Can't run add-on behind corporate proxy

### ISSUE THREAD

**Issue by pelicangris** [microsoft/vscode-powerquery-sdk#265]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.2.2

### Platform

Windows

### Architecture

i86

### OS Version

WINDOWS 10

### VSCode version

1.77.0

### Bug Description

I have been unable to get the add-on to work within my corporate network and facing an error: Failed to update PowerQuery.sdkTools package due to unable to get issuer certificate.

I have adjusted the proxy settings in VSCode as per the below:
Proxy: http://[REDACTED]
Proxy Authorization: untouched
Proxy Strict All: unticked
Proxy Support: on
System Certificates: ticked

Any advice would be very much appreciated!

### Steps to Reproduce

I have adjusted the proxy settings in VSCode as per the below:
Proxy: http://[REDACTED]
Proxy Authorization: untouched
Proxy Strict All: unticked
Proxy Support: on
System Certificates: ticked

### Actual Experience

As I navigate to a project folder and select "Evaluate current file", I get the error message: Failed to update PowerQuery.SdkTools package due to unable to get issuer certificate.

### Expected Experience

I would expect for the add-on to run and to build my custom connector.

### Additional Context

Running behind a corporate proxy.

**Comment by mattmasson** [comment]
@albertli-msft we should honor the common VS Code proxy settings (`http.proxy`, `http.proxySupport`, and others) in the calls we make to nuget.

**Comment by mattmasson** [comment]
@pelicangris you might be able to workaround this problem using the nuget.exe command line tool. 

- Download nuget.exe from https://www.nuget.org/downloads and save it locally (i.e. `c:\tools`)
- Configure the default proxy settings to use for nuget.exe ([stackoverflow example](https://stackoverflow.com/questions/9232160/nuget-behind-a-proxy), [nuget reference](https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#config-section))
- Test nuget.exe from the command line to make sure the proxy settings are working
- In VS Code, set the `powerquery.sdk.externals.nugetPath` configuration setting to the directory containing nuget.exe (`c:\tools`)

When you override `powerquery.sdk.externals.nugetPath` the tool will make nuget calls via nuget.exe, rather than calling out directly to the REST API. We made the direct REST calls our default behavior to make it easier to get started.

**Comment by pelicangris** [comment]
Just wanted to report that installing nuget and adjusting the nugetpath in the VSCode config did the trick. Thanks for the pointer!

**Comment by albertli-msft** [comment]
Hi @pelicangris, 

Thanks for using Power Query SDK, 

Currently we only support use the http client to seize the nuget package behind the proxy w/o using nuget.exe.

I am using fiddler proxy here as an example:

Configure the setting item "http.proxy" following the pattern of  http://<username>:<password>@<domain or ip address> like http://1:1@127.0.0.1:8888 in my local fiddler case.
![image](https://user-images.githubusercontent.com/69623692/235089085-8772159a-d45b-4252-b5b6-1b758a4d214f.png)

And, also, leave the nuget.exe path blank:
![image](https://user-images.githubusercontent.com/69623692/235089984-2c5954c5-8391-4e1f-b138-9f6ad00807ca.png)

Then the extension should be able to pick up the nuget package behind the proxy like in the video clip attached:

https://user-images.githubusercontent.com/69623692/235090116-44cdf3b1-cc4c-4f7e-b510-ed961b338565.mp4

The extension of version 0.2.3 is able to seize the nuget package behind my fiddle proxy server of basic auth.

btw, the extension would also respect the "http.proxyAuthorization" config item if you need it.

Have a good one. 😀
