### ISSUE TITLE
Example code of data connector for updating ui with download progress?

### ISSUE THREAD

**Issue by StephenOTT** [microsoft/vscode-powerquery-sdk#310]
Is there some code showing how to update the UI with download progress?

Example would be something like pagination of web.contents.  How do we show amount of data, rows, page, etc message in the UI that we see in other published connectors?

Thanks

**Comment by mattmasson** [comment]
There is no way for connectors to report progress messages today.

Certain metrics (like bytes read, memory usage, etc.) should come automatically from the underlying M engine functions (like `Web.Contents`). Other metrics (like row count) are reported at the data reader level rather than the connector.

We have multiple backlog items in this area, but they are pretty far down in the priority list.

The best a connector can do today is write trace messages out with `Diagnostics.Trace` or one of the wrappers in the [Diagnostics.pqm sample](https://github.com/microsoft/DataConnectors/blob/master/samples/ODBC/SqlODBC/Diagnostics.pqm).
